# Generated by Django 4.2.3 on 2023-08-11 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employees", "0002_alter_employee_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="manager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees_manager",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
