# Generated by Django 4.2.2 on 2023-07-27 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_alter_employee_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="employees.city"
            ),
        ),
    ]
