# Generated by Django 4.2.3 on 2023-08-30 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_alter_employee_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="employment_type",
            field=models.IntegerField(
                choices=[(1, "fulltime"), (2, "parttime")], default=1
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="start_date",
            field=models.DateTimeField(default=datetime.date(2022, 1, 1)),
            preserve_default=False,
        ),
    ]
