# Generated by Django 4.2.3 on 2023-08-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_employee_employment_type_employee_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="start_date",
            field=models.DateField(),
        ),
    ]
