# Generated by Django 4.2.2 on 2023-07-27 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0008_state_alter_employee_city_alter_city_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="city",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="employees.city",
            ),
        ),
    ]
