# Generated by Django 4.2.2 on 2023-07-27 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0011_alter_employee_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employees.city",
            ),
        ),
    ]
