# Generated by Django 4.2.2 on 2023-07-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0013_remove_state_name_state_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="state",
            field=models.IntegerField(
                choices=[
                    (0, "Baden-Württemberg"),
                    (1, "Bavaria (Bayern)"),
                    (2, "Berlin"),
                    (3, "Brandenburg"),
                    (4, "Bremen"),
                    (5, "Hamburg"),
                    (6, "Hesse (Hessen)"),
                    (7, "Lower Saxony (Niedersachsen)"),
                    (8, "Mecklenburg-Western Pomerania (Mecklenburg-Vorpommern)"),
                    (9, "North Rhine-Westphalia (Nordrhein-Westfalen)"),
                    (10, "Rhineland-Palatinate (Rheinland-Pfalz)"),
                    (11, "Saarland"),
                    (12, "Saxony (Sachsen)"),
                    (13, "Saxony-Anhalt (Sachsen-Anhalt)"),
                    (14, "Schleswig-Holstein"),
                    (15, "Thuringia (Thüringen)"),
                ]
            ),
        ),
    ]
