# Generated by Django 4.2.2 on 2023-07-27 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacations", "0015_remove_publicholidays_states_publicholidays_cities"),
        ("employees", "0014_alter_city_state"),
    ]

    operations = [
        migrations.DeleteModel(
            name="State",
        ),
    ]
