# Generated by Django 4.2.2 on 2023-08-01 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0018_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
