# Generated by Django 4.2.2 on 2023-07-11 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicHolidays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city",
                    models.IntegerField(
                        choices=[
                            (0, "Bonn"),
                            (1, "Hamburg"),
                            (2, "Frankfurt"),
                            (3, "Munich"),
                        ]
                    ),
                ),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Vacation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "full_day",
                    models.DecimalField(decimal_places=1, default=1, max_digits=1),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "Vacation"), (2, "Special leave")], default=1
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExtraDays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allotted_days",
                    models.DecimalField(decimal_places=1, default=30, max_digits=2),
                ),
                (
                    "transferred_days",
                    models.DecimalField(decimal_places=1, default=0, max_digits=2),
                ),
                ("year", models.IntegerField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                    ),
                ),
            ],
        ),
    ]
