# Generated by Django 4.2.3 on 2023-08-01 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "full_day",
                    models.DecimalField(
                        choices=[(1, "1.0"), (0.5, "0.5")],
                        decimal_places=1,
                        default=1,
                        max_digits=2,
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "Vacation"), (2, "Special leave")], default=1
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublicHolidays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("cities", models.ManyToManyField(to="employees.city")),
            ],
            options={
                "verbose_name_plural": "Public holidays",
            },
        ),
        migrations.CreateModel(
            name="AvailableDays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allotted_days", models.IntegerField(default=30)),
                (
                    "transferred_days",
                    models.DecimalField(decimal_places=1, default=0, max_digits=2),
                ),
                ("year", models.IntegerField(default=2023)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Available days",
                "unique_together": {("employee", "year")},
            },
        ),
    ]
