# Generated by Django 4.2.3 on 2023-08-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicholidays",
            name="every_year",
            field=models.BooleanField(default=False),
        ),
    ]
