# Generated by Django 4.2.2 on 2023-07-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacations", "0002_publicholidays_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publicholidays",
            name="year",
        ),
    ]
