# Generated by Django 4.2.3 on 2023-08-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacations", "0003_transferdaysrequest_deletedaysrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacation",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
