# Generated by Django 4.2.2 on 2023-07-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacations", "0004_alter_availabledays_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="extradays",
            options={"verbose_name_plural": "Available days"},
        ),
    ]
