# Generated by Django 4.2.3 on 2023-08-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacations", "0005_vacation_created_at_vacation_last_modified_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="description",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
