# Generated by Django 4.2.2 on 2023-07-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacations", "0005_alter_availabledays_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacation",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
