# Generated by Django 4.2.2 on 2023-07-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacations", "0006_alter_vacation_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacation",
            name="full_day",
            field=models.DecimalField(
                choices=[(1, "1.0"), (0.5, "0.5")],
                decimal_places=1,
                default=1,
                max_digits=2,
            ),
        ),
    ]
