# Generated by Django 4.2.3 on 2023-08-09 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacations", "0006_alter_request_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transferdaysrequest",
            name="employee",
        ),
        migrations.DeleteModel(
            name="DeleteDaysRequest",
        ),
        migrations.DeleteModel(
            name="TransferDaysRequest",
        ),
    ]
