# Generated by Django 4.2.2 on 2023-07-21 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacations", "0007_alter_vacation_full_day"),
    ]

    operations = [
        migrations.RenameModel('ExtraDays', 'AvailableDays')
    ]
