# Generated by Django 4.2.2 on 2023-07-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
        ("vacations", "0008_auto_20230721_1710"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availabledays",
            name="allotted_days",
            field=models.IntegerField(default=30),
        ),
        migrations.AlterUniqueTogether(
            name="availabledays",
            unique_together={("employee", "year")},
        ),
    ]
