# Generated by Django 4.2.3 on 2023-08-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacations", "0008_rename_vacation_vacationday"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="request_status",
            field=models.IntegerField(
                choices=[(1, "pending"), (2, "approved"), (3, "rejected")], default=1
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="request",
            name="request_type",
            field=models.IntegerField(
                choices=[(1, "vacation"), (2, "transfer"), (3, "cancel")], default=1
            ),
        ),
    ]
