# Generated by Django 4.2.3 on 2023-08-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacations", "0009_request_request_status_alter_request_request_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="request_status",
            field=models.IntegerField(
                choices=[(1, "pending"), (2, "approved"), (3, "rejected")], default=1
            ),
        ),
    ]
