# Generated by Django 4.2.2 on 2023-07-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacations", "0009_alter_availabledays_allotted_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicholidays",
            name="name",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
