# Generated by Django 4.2.3 on 2023-08-28 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_alter_employee_manager"),
        ("vacations", "0010_alter_request_request_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availabledays",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="available_days",
                to="employees.employee",
            ),
        ),
        migrations.AlterField(
            model_name="availabledays",
            name="transferred_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="request",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="employees.employee",
            ),
        ),
        migrations.AlterField(
            model_name="vacationday",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vacation_days",
                to="employees.employee",
            ),
        ),
    ]
