# Generated by Django 4.2.2 on 2023-07-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacations", "0010_publicholidays_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicholidays",
            name="name",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
