# Generated by Django 4.2.2 on 2023-07-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_alter_employee_city"),
        ("vacations", "0011_alter_publicholidays_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publicholidays",
            name="city",
        ),
        migrations.AddField(
            model_name="publicholidays",
            name="cities",
            field=models.ManyToManyField(to="employees.city"),
        ),
    ]
