# Generated by Django 4.2.2 on 2023-07-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacations", "0012_remove_publicholidays_city_publicholidays_cities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicholidays",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
