# Generated by Django 4.2.3 on 2023-08-31 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_alter_employee_start_date"),
        ("vacations", "0012_alter_availabledays_allotted_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="availabledays",
            name="remote_work_days",
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name="request",
            name="request_type",
            field=models.IntegerField(
                choices=[
                    (1, "vacation"),
                    (2, "transfer"),
                    (3, "cancel"),
                    (4, "remote_work"),
                ],
                default=1,
            ),
        ),
        migrations.CreateModel(
            name="RemoteDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "description",
                    models.TextField(blank=True, max_length=200, null=True),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                    ),
                ),
            ],
        ),
    ]
