# Generated by Django 4.2.3 on 2023-09-01 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacations", "0013_availabledays_remote_work_days_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vacationday",
            old_name="full_day",
            new_name="duration",
        ),
    ]
