# Generated by Django 4.2.2 on 2023-07-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0008_state_alter_employee_city_alter_city_state"),
        ("vacations", "0013_alter_publicholidays_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publicholidays",
            name="cities",
        ),
        migrations.AddField(
            model_name="publicholidays",
            name="states",
            field=models.ManyToManyField(to="employees.state"),
        ),
    ]
