# Generated by Django 4.2.2 on 2023-07-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0014_alter_city_state"),
        ("vacations", "0014_remove_publicholidays_cities_publicholidays_states"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publicholidays",
            name="states",
        ),
        migrations.AddField(
            model_name="publicholidays",
            name="cities",
            field=models.ManyToManyField(to="employees.city"),
        ),
    ]
