# Generated by Django 4.2.3 on 2023-09-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacations", "0014_rename_full_day_vacationday_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="remoteday",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
