# Generated by Django 4.2.2 on 2023-07-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacations", "0015_remove_publicholidays_states_publicholidays_cities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availabledays",
            name="year",
            field=models.IntegerField(default=2023),
        ),
    ]
